### ISSUE TITLE
FBM get3 doesn't work

### ISSUE THREAD

**Issue by NewKrok** [FarazzShaikh/three-noise#1]
Looks like it should be Vector3
https://github.com/FarazzShaikh/three-noise/blob/e12385a2b12f87417eaa3a88f91bbac708bcd125/src/FBM.js#L83

Error message:
```three-noise.module.js:423 Uncaught Input to Perlin::get3() must be of type THREE.Vector3```

**Comment by FarazzShaikh** [comment]
Indeed it should, will fix

**Comment by FarazzShaikh** [comment]
Fixed in release 1.1.1
