### ISSUE TITLE
Using this in a THREE.js project ' Multiple instances of Three.js being imported.'

### ISSUE THREAD

**Issue by fariskas** [FarazzShaikh/three-noise#2]
Hello,

I am trying  to use this library in an existing three.js project, having installed it via npm, and included it in my code,
 
I am getting a `WARNING: Multiple instances of Three.js being imported.`

Checking the `three-noise` module files, i waw that this library also imports threejs within it. Will this be an issue in regards to duplication of library imports?

**Comment by drone1** [comment]
THREE.js is quite massive and so this is quite a problem for bundle size, having 2 different versions of THREE.js loaded and fighting each other. Is this something you plan to look into? It would be great if your library could take THREE as an argument for initialization, and simply try to use that, for example. Thanks a lot!

**Comment by FarazzShaikh** [comment]
This project was created when I was a noob and is now read-only untill I have some time to bring it up to modern standards. Feel free to become a [sponsor](https://github.com/sponsors/FarazzShaikh) or reach out via [email](mailto:farazzshaikh@gmail.com) if you'd like to fund its developement.

Thanks for your intrest in my library 🙌
