### ISSUE TITLE
Use three as a peerDependency instead of dependency

### ISSUE THREAD

**Issue by jsulpis** [FarazzShaikh/three-noise#3]
This would allow the users to choose their version of `three` instead of imposing yours. 

And in many cases, this would avoid to download (and [execute](https://github.com/FarazzShaikh/three-noise/issues/2)) two versions of `three` (since it is in 0.x version, the caret `^` matches only patch versions so `^0.128.0` will likely be different from the user's version)

WYT ?

**Comment by FarazzShaikh** [comment]
I agree with this, infact it’s the right way but this project is pretty much deprecated, it’s functionality will eventually be provided by a future release of https://github.com/FarazzShaikh/glNoise when ever I find the time 

For now you can just download the Perlin noise class and use it as is if you really need to

**Comment by jsulpis** [comment]
Oh cool, I did not know your other library. 
Indeed I imported the file I need in my project instead of using the npm package.
Thanks !
